version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
  pre_build:
    commands:
      - cd deployment
      - ./run-unit-tests.sh
  build:
    commands:
      - . ${CODEBUILD_SRC_DIR}/.env
      - ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION

artifacts:
  files:
      - '**/*'